### ISSUE TITLE
handle if invalid YAML passed in

### ISSUE THREAD

**Issue by ejfrancis** [intuit/judo#5]
tests should fail with non-zero exit code and explanation of the problem if bad YAML indentation found, right now it just throws an unhandled exception if given this:

``` yaml
  npm_postCheckout_Sandbox_CreateStory_Title_GitStatusCheck:
    cwd: ./judo-temp/judo-githooks-npm-sandbox
    command: git status
    outputContains:
  - /On branch ZZZ-[0-9]{0,10}\/no-id/
```
