### ISSUE TITLE
Include test suite YAML file fragments 

### ISSUE THREAD

**Issue by ejfrancis** [intuit/judo#6]
Since mulitple test suites may require similar repeated setup, being able to move repeated things like `prerequisites` into a file and include it, with variable substitution, would be helpful.

example:

**judo-tests/fragments/create-temp-file.yml**

``` yaml
 - mkdir -p temp-dir
 - echo "{{fileContent}}" >> temp-dir/temp-file.txt
```

**judo-tests/some-test.yml**

``` yaml
run:
  some_test_case:
    prerequisiteCwd: .
    prerequisites: 
      - $include ./fragments/create-temp-file.yml
         vars:
          - fileContent: "this will be in the temp-file.txt"
      - npm i
    cwd: ./judo-temp
    command: cat temp-dir/temp-file.txt
    expectCode: 0
    outputContains:
    - this will be in the temp-file.txt
```

---

the resulting YAML would look like this:

``` yaml
run:
  npm_commitMsg_addIdToMsg:
    prerequisiteCwd: .
    prerequisites: 
      - mkdir -p temp-dir
      - echo "this will be in the temp-file.txt" >> temp-dir/temp-file.txt
      - npm i
    cwd: ./judo-temp
    command: cat temp-dir/temp-file.txt
    expectCode: 0
    outputContains:
    - this will be in the temp-file.txt
```
